# Generated by Django 5.2.8 on 2025-11-19 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('department_admin', 'Department Admin'), ('inventory_admin', 'Inventory Admin')], max_length=20)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('balance_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=20)),
                ('opening_inventory', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_meters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_klg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('procurement_suggestion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
            options={
                'db_table': 'inventory_balance',
            },
        ),
    ]
