# Generated by Django 5.1.7 on 2025-11-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('department_admin', 'Department Admin'), ('inventory_admin', 'Inventory Admin')], max_length=50)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
