# Generated by Django 5.1.7 on 2025-11-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='admins',
        ),
    ]
